#!/bin/sh

# ------------------------------------------------------------
# cawk is subjet to a MIT open-source licence
# please refer to the MIT licence file for further information
# 
# this program checks if the main tools are available
# and if the system is ready to run cawk
# ------------------------------------------------------------
#

echo "cawk -----------------------------------"
echo "cawk : check if the main tools are there"
echo "cawk : all should be available/OK"
echo "cawk check system start ----------------"

if command -v find >/dev/null 2>&1; then
    echo "OK : find is available."
else
    echo "NOK : find is not available."
fi

if command -v m4 >/dev/null 2>&1; then
    echo "OK : m4 is available."
else
    echo "NOK : m4 is not available."
fi

if command -v mktemp >/dev/null 2>&1; then
    echo "OK : mktemp is available."
else
    echo "NOK : mktemp is not available."
fi

if command -v gmake >/dev/null 2>&1; then
    echo "OK : gmake is available."
else
    echo "NOK : gmake is not available."
fi

if command -v gawk >/dev/null 2>&1; then
    echo "OK : gawk is available."
else
    echo "NOK : gawk is not available."
fi

if command -v sed >/dev/null 2>&1; then
    echo "OK : sed is available."
else
    echo "NOK : sed is not available."
fi
if command -v diff >/dev/null 2>&1; then
    echo "OK : diff is available."
else
    echo "NOK : diff is not available."
fi
if command -v egrep >/dev/null 2>&1; then
    echo "OK : egrep is available."
else
    echo "NOK : egrep is not available."
fi
if command -v grep >/dev/null 2>&1; then
    echo "OK : grep is available."
else
    echo "NOK : grep is not available."
fi
echo "cawk check system end ------------------"
