#!/bin/sh
# ------------------------------------------------------------
# cawk is subjet to a MIT open-source licence
# please refer to the MIT licence file for further information
#
# cawk is Copyright (C) 2024 by Cedric Llorens
# ------------------------------------------------------------
#

echo "cawk -----------------------------------"
echo "cawk : check if the main tools are there"
echo "cawk : all should be available/green"
echo "cawk check system start ----------------"

if command -v find >/dev/null 2>&1; then
    echo "\033[0;32m'find' is available.\033[0m"
else
    echo "\033[0;31m'find' is not available.\033[0m"
fi

if command -v mktemp >/dev/null 2>&1; then
    echo "\033[0;32m'mktemp' is available.\033[0m"
else
    echo "\033[0;31m'mktemp' is not available.\033[0m"
fi

if command -v gmake >/dev/null 2>&1; then
    echo "\033[0;32m'gmake' is available.\033[0m"
else
    echo "\033[0;31m'gmake' is not available.\033[0m"
fi

if command -v gawk >/dev/null 2>&1; then
    echo "\033[0;32m'gawk' is available.\033[0m"
else
    echo "\033[0;31m'gawk' is not available.\033[0m"
fi

if command -v sed >/dev/null 2>&1; then
    echo "\033[0;32m'sed' is available.\033[0m"
else
    echo "\033[0;31m'sed' is not available.\033[0m"
fi
echo "cawk check system end ------------------"
