.PHONY: all install

all:
	# nothing to do

install:
	cp fw_*cisco-ios*template ../../tests.cisco-ios/repo
	cp fw_*huawei-vrp*template ../../tests.huawei-vrp/repo

clean:
	rm -f ../../tests.cisco-ios/repo/fw_*template
	rm -f ../../tests.huawei-vrp/repo/fw_*template
